version: '3.8'

services:
  nginx:
    depends_on:
      - php
    build:
      context: docker/nginx
      dockerfile: Dockerfile
    container_name: nginx
    tty: true
    stdin_open: true
    env_file: .env
    working_dir: ${PHP_USER_HOME_DIRECTORY}
    restart: always
    volumes:
      - ./docker/nginx/prod:/etc/nginx/conf.d
      - ./src:${PHP_USER_HOME_DIRECTORY}
      - /home/php/vendor
      - ./ssl:/etc/letsencrypt/live/togetherandstronger.site
    ports:
      - '80:80'
      - '443:443'

  php:
    depends_on:
      - mysql
    build:
      context: docker/php
      dockerfile: Dockerfile
      args:
        PHP_USER_NAME: $PHP_USER_NAME
        PHP_USER_IDENTIFIER: $PHP_USER_IDENTIFIER
        PHP_USER_SHELL: $PHP_USER_SHELL
        PHP_USER_HOME_DIRECTORY: $PHP_USER_HOME_DIRECTORY
    container_name: php
    restart: always
    tty: true
    env_file: .env
    stdin_open: true
    working_dir: ${PHP_USER_HOME_DIRECTORY}
    user: php
    volumes:
      - ./src:${PHP_USER_HOME_DIRECTORY}
      - /home/php/vendor

  mysql:
    container_name: mysql
    restart: always
    build:
      context: docker/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./logs:/var/log/mysql
      - ./docker/mysql/conf.d:/etc/mysql/conf.d
    ports:
      - ${MYSQL_PORT}:${MYSQL_PORT}
    expose:
      - '${MYSQL_PORT}'

  adminer:
    container_name: adminer
    image: adminer:latest
    restart: always
    environment:
      ADMINER_DEFAULT_SERVER: mysql
      ADMINER_DESIGN: arcs-material
    ports:
      - '${ADMINER_PORT}:${ADMINER_PORT}'
