version: '3.8'

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile.php
    container_name: php
    image: php
    restart: always
    tty: true
    working_dir: /home/php/src
    entrypoint: php
    volumes:
      - .:/home/php
    ports:
      - '${PHP_PORT}:${PHP_PORT}'
    env_file: .env
    command: -S 0.0.0.0:${PHP_PORT}

  mysql:
    container_name: mysql
    image: mysql
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.sql
      target: sql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      env_file: .env
    volumes:
      - ./init.sql:/data/application/init.sql
      - ./logs:/var/log/mysql
    ports:
      - ${MYSQL_PORT}:${MYSQL_PORT}
    expose:
      - '${MYSQL_PORT}'
