version: '3.8'

services:
  php:
    container_name: php
    image: php
    restart: always
    working_dir: /var/www/
    build:
      context: .
      dockerfile: Dockerfile.php
    ports:
      - '${PHP_PORT}:80'
    env_file: .env
  mysql:
    container_name: mysql
    image: mysql
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.sql
      target: sql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      env_file: .env
    volumes:
      - ./data:/var/lib/mysql
      - ./logs:/var/log/mysql
    ports:
      - ${MYSQL_PORT}:${MYSQL_PORT}
    expose:
      - '${MYSQL_PORT}'
